modLoader="javafml"
loaderVersion="[37,)"
license="LGPL-3.0-or-later"
issueTrackerURL="https://github.com/DrunkBlood/Netherite-Elytra/issues"
logoFile="${mod_icon}"
[[mods]]
modId="${mod_id}"
version="${version}"
displayName="${mod_name}"
displayURL="${mod_url}"
authors="${mod_author}"
description='''
${mod_description}
'''
[[dependencies.netherelytra]]
    modId="forge"
    mandatory=true
    versionRange="[37,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.netherelytra]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.17.1,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.netherelytra]]
    modId="caelus"
    mandatory=true
    versionRange="[1.17.1-3.0.0.1,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.netherelytra]]
    modId="curios"
    mandatory=true
    versionRange="[1.17.1-5.0.1.0,)"
    ordering="NONE"
    side="BOTH"